version: '3.2'
services:
  manager:
    image: manager
    container_name: manager
    expose:
     - 5010
    ports:
     - "5010:5010"

  pmf_processor:
    image: pmf_processor
    container_name: pmf_processor
    expose:
     - 8100
    ports:
     - "8100:8100"
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus:/etc/config/
      - ./data:/data
    command:
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=2h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.listen-address=:9001'
      - '--storage.tsdb.min-block-duration=5m'
      - '--storage.tsdb.max-block-duration=5m'
    restart: unless-stopped
    expose:
      - 9001
    ports:
      - "9001:9001"

  thanos_receive:
    image: thanosio/thanos:v0.29.0
    container_name: thanos_receive
    command:
      - receive
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --remote-write.address=0.0.0.0:19291
      - --receive.replication-factor=1
      - --label=receive="true"
      - --tsdb.path=/tmp/receive
      - --tsdb.retention=15d
      - --receive.local-endpoint=thanos-receive:10901
    healthcheck:
      test: wget -q -O- localhost:10902/-/ready
      interval: 10s
      timeout: 5s
      retries: 3

  thanos_query:
    image: thanosio/thanos:v0.29.0
    container_name: thanos_query
    command:
      - "query"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--grpc-address=:20901"
      - "--http-address=:19192"
      - "--store=thanos_receive:10901"
      # - "--store=thanos_rule:10901"
      - "--store.sd-interval=5m"
      - "--query.replica-label=monitor"
    expose:
      - 20901
      - 19192
    healthcheck:
      test: wget -q -O- localhost:19192/-/ready
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "19192:19192"
  
  alertmanager:
    image: "quay.io/prometheus/alertmanager:v0.25.0"
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    healthcheck:
      test: wget -q -O- localhost:9093/-/ready
      interval: 10s
      timeout: 5s
      retries: 3
  
  ruler_config:
    image: ruler_config 
    container_name: ruler_config
    environment:
      - HOST=0.0.0.0
      - PORT=8090
      - RULES_FOLDER=/shared
      - THANOS_RULE_URL=http://thanos_ruler:10903
      - LOG_FILE=ruleTranslator.log
    volumes:
      - shared-data:/shared
    expose:
      - 8090
    ports:
      - "8090:8090"

  thanos_ruler:
    image: thanosio/thanos:v0.29.0
    container_name: thanos_ruler
    command:
      - "rule"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--grpc-address=:30901"
      - "--http-address=:10903"
      - "--query=thanos_query:19192"
      - "--rule-file=/shared/rules.yml"
      - "--alertmanagers.url=http://alertmanager:9093"
    volumes:
      - shared-data:/shared
    expose:
      - 30901
      - 10903
    healthcheck:
      test: wget -q -O- localhost:10903/-/ready
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "10903:10903"  


volumes:
  shared-data:
